# Generated by Django 4.2 on 2023-10-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(verbose_name='Создано')),
                ('time_write', models.DateTimeField(auto_now=True, verbose_name='Добавлено')),
                ('usd', models.DecimalField(decimal_places=10, max_digits=60, verbose_name='Курс USD к рублю')),
                ('eur', models.DecimalField(decimal_places=10, max_digits=60, verbose_name='Курс EUR к рублю')),
            ],
            options={
                'verbose_name': 'Курс валют ',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['time_create'],
            },
        ),
    ]
